<?php
/**
 * Created by PhpStorm.
 * User: 15318
 * Date: 2017/9/29
 * Time: 10:11
 *子类继承父类：当一个子类继承父类的时候，它可以使用父类的属性和方法，
 */
class Person{
    public $name;
    public $age;
    public $sex;
 function Person($name="",$age="",$sex=""){
        $this->name=$name;
        $this->age=$age;
        $this->sex=$sex;
    }
//统一的构造方法
/*    public function __construct()

    {

    }*/

    //普通方法
    function hao(){
        echo $this->name."".$this->age."".$this->sex;

    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * @param mixed $age
     */
    public function setAge($age)
    {
        $this->age = $age;
    }

    /**
     * @return mixed
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * @param mixed $sex
     */
    public function setSex($sex)
    {
        $this->sex = $sex;
    }
}


//继承preson类：
class Doctor extends Person{
    public $angel;
    public $beautiful;
        //重写方法， 没有person
             public function __construct($name = "", $age = "", $sex = "")
                {
                  parent::__construct($name, $age, $sex);
             }

                  function hao()
                 {
                      parent::hao(); // TODO: Change the autogenerated stub
                   }

    /*
     * 一个方法如果不修饰权限。默认的是public
     */
    //doctor 的其他方法：
     public function kanbing(){
                 echo "看病";
        }
}
//创建了一个实例，Doctor同样继承preson的方法。
$myDoctor=new Doctor("赵",20,"女");
$myDoctor->hao();

?>